### This is fully build docker file with all the app and code installed 

#FROM ubuntu:latest
# USING MY IMAGE becasue below code is already installed in this image 
# you can use ubuntu latest and uncomment the below line of installation of php pakacges and nginx 
FROM noscopev6/ubuntu-php-todo
# # Update the package list and install necessary software
# RUN apt-get update && apt-get install -y software-properties-common
# RUN add-apt-repository ppa:ondrej/php

# # Update the package list again
# RUN apt-get update -y 

# # Install Nginx, PHP 8.0, and necessary extensions
# RUN apt-get install -y nginx php8.0-fpm php8.0-mysql

RUN rm -rf /var/www/html/*
RUN rm -rf  /etc/nginx/sites-available/default
COPY ./nginx-default.conf /etc/nginx/sites-available/default
COPY ./web-app /var/www/html
RUN chown -R www-data:www-data /var/www/html
# Expose port 80 for Nginx
EXPOSE 80

# Start Nginx and PHP-FPM
CMD service nginx start && service php8.0-fpm start && tail -f /dev/null

# Start Nginx when the container starts
#CMD ["nginx", "-g", "daemon off;"]


